### PR TITLE
New development-related icons.

### PR DESCRIPTION
**Pull request by jolkdarr**
Contributions for issue #106.

### CODE REVIEW

**Comment by alecive** [comment]
Wow! This was is a big pull request. I'll quickly go through it, and then I'll merge it, thanks!

**Comment by alecive** [comment]
@jolkdarr here is my list of comments:

 * some icons does not seem to belong to the correct directory. Eg:
    * what is `applications-mathematica.svg` about? Is that about the proper application? if so, why the icon is using a file icon?
    * why `perl` `file-c++`, `file-scala`, `file-python` are under the `applications` folder and not `mimetypes`? If they were mimetypes, they should use `icon-template-file`, otherwise if they are for apps they should use `icon-template.svg`
 * some applications are simply the original logo with some long shadow. Please try to follow the `Flatwoken` design, with flat icons, and as little bells and whistles as possible. E.g.:
    * `dmd-doc` would be better if you use a red background and then you put the white "D" with the shadow
    * `erlang`, `mono-runtime-common`: see dmd-doc
    * `dmd-doc` `file-python`has two shadows: one shadow around the shape, and another long shadow. This does not really make much sense to me. Please remove the one around the shape: although I like it, it is drastically in contrast with the overall style of the icon pack.
   * `pgadmin3` could be simplified (e.g. remove the black border)
   * `rlogo_icon`, `application-ecmascript.svg` could be simplified 
 * `emblem-database` has a too big inner icon (it should be no more than 300px). Further, it should be more similar to the already available `file-db.svg` icon
 * `application-x-dbf` should link to `file-db.svg`
 * `emblem-ruby` should link to the already available `ruby` icon
 * some of the icons are using a lot of color gradients. Please change them to flat, pleasant colors if possible. E.g.: `emblem-database`
 * `application-json` should be simplified (even if I don't know how, maybe it would be better to use some curly brackets as in `ide.svg`)

Ok I think for the time being this list is enough. When you will finish these, I will list the rest of the issues :)

**Comment by jolkdarr** [comment]
First: thanks for your comments.

Mathematica icons were badly handled.
- application icon is in the apps folder,
- notebook icon is in the mimetypes folder.

MIME types fulfill Wolfram specifications (https://reference.wolfram.com/language/ref/format/NB.html).

For the application, a new link is added because my (quite old) version (7.0) expects an icon named '''wolfram_mathematica".

Some fixes in next push...

**Comment by jolkdarr** [comment]
Perl, C++, Scala file icons moved to mimetypes folder.

Python file removed (you have provided already a version in apps).
=> *Do you wish I move the file-python.svg in mimetypes folder as well or is there a reason to keep it in apps?*

Next fix tomorrow ;)

**Comment by alecive** [comment]
@jolkdarr sorry for the delay, I don't know why I didn't notice all your changes up to now. Anyway, coming back to the topic, all these commits are too many to be merged into FlatWoken as-is. 

If you are still interested into merging your work with the main repository, do you mind splitting them up in more atomic pull requests? If we can discuss about the icons one by one I can provide better feedback and we can merge more quickly.

Closing for now.

**Pull request closed without merging**
