### PR TITLE
Added Visual Studio Code icon

### PR DESCRIPTION
**Pull request by gustavosotnas**
[Visual Studio Code](https://code.visualstudio.com) is a new Sublime Text-like text editor for front-end developers, made by Microsoft and _open-source_ community for Windows, Linux and Mac OS X.

I made this icon using Inkscape.

### CODE REVIEW

**Comment by alecive** [comment]
Thanks for the contribution @gustavosotnas !!

Couple questions:

 1. Is blue the default color for vscode? Isn't it purple-ish?
 2. Good job in creating one `code.svg` icon and then symlinking it to `vscode.svg` and `visual-studio-code.svg`. My only concern is in this case about having a generic `code` icon related to visual studio code, which seems a bit of a stretch to me. What about having the svg icon in `vscode.svg` and symlinking it only to `visual-studio-code.svg` (without having `code.svg` altogether)?

**Comment by gustavosotnas** [comment]
You're welcome @alecive !

Answering your questions:
1. Yes, [Visual Studio Code](https://code.visualstudio.com) icon uses `#0271bc` HEX color, and I used this color in svg. It's different from [Visual Studio IDE](https://visualstudio.com) icon color, that uses `#865fc5` HEX color. They are different software.  

| visual-studio-2017-icon | visual-studio-code |
|:----:|:----:|
| Visual Studio | Visual Studio Code |

2. I can rename `code.svg` to `vscode.svg` and symlink it to `code.svg` and `visual-studio-code.svg`, but is necessary to have the file `code.svg` because in a installation of Visual Studio Code in Linux, the [.deb](https://code.visualstudio.com/docs/?dv=linux64_deb) or [.rpm](https://code.visualstudio.com/docs/?dv=linux64_rpm) package creates a `code.desktop` file in `/usr/share/applications`, that has the following content:
```desktop
[Desktop Entry]
Name=Visual Studio Code
Comment=Code Editing. Redefined.
GenericName=Text Editor
Exec=/usr/share/code/code --unity-launch %U
Icon=code
Type=Application
StartupNotify=true
StartupWMClass=Code
Categories=Utility;TextEditor;Development;IDE;
MimeType=text/plain;inode/directory;
Actions=new-window;
Keywords=vscode;

X-Desktop-File-Install-Version=0.22

[Desktop Action new-window]
Name=New Window
Name[de]=Neues Fenster
Name[es]=Nueva ventana
Name[fr]=Nouvelle fenêtre
Name[it]=Nuova finestra
Name[ja]=新規ウインドウ
Name[ko]=새 창
Name[ru]=Новое окно
Name[zh_CN]=新建窗口
Name[zh_TW]=開新視窗
Exec=/usr/share/code/code --new-window %U
Icon=code
```
As we can see in the 6<sup>th</sup> line, without the icon `code.svg`, it opens the `code.png` file, located in `/usr/share/pixmaps`. Because of that we have to use **`code.svg`**, otherwise, the icon (`.desktop` file) will load the pixmap one.

**Comment by alecive** [comment]
Yes, your comment was perfect! Thanks again for the contribution, I'll merge it now. Feel free to add more in the future!

**Comment by gustavosotnas** [comment]
@alecive Yes, I have more icons that I created in these guidelines over the time (I use FlatWoken for 3 years and until today it fits perfect with cairo-dock in my Linux Mint), so, this is just the first of many PRs that I will do to your repository! :wink:

**Pull request merged**
