### PR TITLE
Added minecraft icon

### PR DESCRIPTION
**Pull request by f43792**
Minecraft icon added to Alessandro evaluation

### CODE REVIEW

**Comment by alecive** [comment]
Thanks @f43792 , the pull request was ok! Feel free to do more than these in the future if you need it :+1: 

Btw the green color over the green logo is not that great imho, what do you think about removing the inner rounded square frame and putting the shadow on the black logo?

**Comment by alecive** [comment]
Or we can put the standard minecraft block (in 2D) as the background, by using these resources:

 * http://images.wikia.com/yogbox/images/d/dd/Minecraft_Block.svg
 * http://uxrepo.com/static/icon-sets/dr-slash/svg/minecraft.svg 

What do you think?

**Comment by f43792** [comment]
Hey @alecive, thanks by feedback.
The black squares, are in the game, holes, so, is not possible to use shadows on it and be consistent  (I asked my 9 year old daughter and she agree .. lol). I will work on two new proposals and sent by pull, ok?

**Comment by f43792** [comment]
@alecive , take a look on some of options. I kind of insist on that initial logo, because it is in fact a character of the game, and every gamer recognizes it...
screenshot from 2015-07-24 01 52 19

Take a look and tell me what do you think. Regards,

**Pull request merged**
