### PR TITLE
Add deadbeef icon

### PR DESCRIPTION
**Pull request by varlesh**
Popular audio player: http://deadbeef.sourceforge.net/
Original logo: 
unnamed

### CODE REVIEW

**Comment by alecive** [comment]
@varlesh  sorry for the super long delay in answering. I really love both the deadbeef and the bomi icon. For viber, I have already my own version (I made it for the Android icon pack), and I pushed it in this commit: 3cb52ef0fca3f8274deb8ae3c7145c2bb1498955
Can you please remove the viber icon from the pull request so that I will be able to safely merge this pull request? Thanks!

**Comment by varlesh** [comment]
Oh, sorry i delete fork long ago. Maybe you merged and add your icon for viber again?

**Comment by alecive** [comment]
Ok, will do!

**Comment by varlesh** [comment]
Thx )

**Comment by alecive** [comment]
Ok done in #108 . Thanks!

**Pull request closed without merging**
